# Use a base image with OpenJDK 21
FROM openjdk:21-jdk-slim as builder

# Set the working directory in the container
WORKDIR /member

# Copy the Gradle build files
COPY build.gradle settings.gradle ./
COPY gradle/ ./gradle/

# Copy the source code
COPY src/ ./src/

# Build the application
RUN ./gradlew build --no-daemon

# Start a new stage from a smaller image
FROM openjdk:21-jre-slim

# Set the working directory
WORKDIR /member

# Copy the compiled JAR file from the builder stage
COPY --from=builder /member/build/libs/*.jar member.jar

# Expose the port that the application runs on
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "member.jar"]